kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/johbro/nginx-simple.git'
    openshift.io/generated-by: OpenShiftWebConsole
  resourceVersion: '204398090'
  name: nginx-simple-git
  uid: 3134e5dc-11c8-4ecd-b9e8-152f0f2bb1e1
  creationTimestamp: '2021-08-10T18:48:18Z'
  generation: 2
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2021-08-10T18:48:18Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:app.openshift.io/vcs-ref': {}
            'f:app.openshift.io/vcs-uri': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/part-of': {}
        'f:spec':
          'f:output':
            'f:to':
              .: {}
              'f:kind': {}
              'f:name': {}
          'f:runPolicy': {}
          'f:source':
            'f:contextDir': {}
            'f:git':
              .: {}
              'f:uri': {}
            'f:type': {}
          'f:strategy':
            'f:dockerStrategy':
              .: {}
              'f:dockerfilePath': {}
            'f:type': {}
          'f:triggers': {}
    - manager: openshift-apiserver
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2021-08-10T18:48:18Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:lastVersion': {}
  namespace: johnswebapp
  labels:
    app: nginx-simple-git
    app.kubernetes.io/component: nginx-simple-git
    app.kubernetes.io/instance: nginx-simple-git
    app.kubernetes.io/part-of: nginx-simple-git-app
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'nginx-simple-git:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/johbro/nginx-simple.git'
    contextDir: /
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: nginx-simple-git-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: nginx-simple-git-github-webhook-secret
    - type: ConfigChange
  runPolicy: Serial
status:
  lastVersion: 1

